
FROM maven:3.9.4-eclipse-temurin-17 as build

WORKDIR /app

COPY . .

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/viatab-backend-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java", "-jar", "viatab-backend-0.0.1-SNAPSHOT.jar"]
