# Build Stage 
FROM maven:3.9.4-eclipse-temurin-17 as build

WORKDIR /app

COPY . .

# Ensuring once again mvnw has correct line endings + is executable
RUN apt-get update && apt-get install -y dos2unix \
  && dos2unix mvnw \
  && chmod +x mvnw

# Build the application (skipping the tests for faster build)
RUN ./mvnw clean package -DskipTests

# Runtime Stage 
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the final built jar from the previous stage
COPY --from=build /app/target/viatab-backend-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java", "-jar", "viatab-backend-0.0.1-SNAPSHOT.jar"]
